import type { CountryCreate } from "@/client"

export const PREDEFINED_COUNTRIES: CountryCreate[] = [
  { name: "Afganistán", alpha_2: "AF", iso_numeric: "004" },
  { name: "Åland", alpha_2: "AX", iso_numeric: "248" },
  { name: "Albania", alpha_2: "AL", iso_numeric: "008" },
  { name: "Alemania", alpha_2: "DE", iso_numeric: "276" },
  { name: "Andorra", alpha_2: "AD", iso_numeric: "020" },
  { name: "Angola", alpha_2: "AO", iso_numeric: "024" },
  { name: "Anguila", alpha_2: "AI", iso_numeric: "660" },
  { name: "Antártida", alpha_2: "AQ", iso_numeric: "010" },
  { name: "Antigua y Barbuda", alpha_2: "AG", iso_numeric: "028" },
  { name: "Arabia Saudita", alpha_2: "SA", iso_numeric: "682" },
  { name: "Argelia", alpha_2: "DZ", iso_numeric: "012" },
  { name: "Argentina", alpha_2: "AR", iso_numeric: "032" },
  { name: "Armenia", alpha_2: "AM", iso_numeric: "051" },
  { name: "Aruba", alpha_2: "AW", iso_numeric: "533" },
  { name: "Australia", alpha_2: "AU", iso_numeric: "036" },
  { name: "Austria", alpha_2: "AT", iso_numeric: "040" },
  { name: "Azerbaiyán", alpha_2: "AZ", iso_numeric: "031" },
  { name: "Bahamas", alpha_2: "BS", iso_numeric: "044" },
  { name: "Bangladés", alpha_2: "BD", iso_numeric: "050" },
  { name: "Barbados", alpha_2: "BB", iso_numeric: "052" },
  { name: "Baréin", alpha_2: "BH", iso_numeric: "048" },
  { name: "Bélgica", alpha_2: "BE", iso_numeric: "056" },
  { name: "Belice", alpha_2: "BZ", iso_numeric: "084" },
  { name: "Benín", alpha_2: "BJ", iso_numeric: "204" },
  { name: "Bermudas", alpha_2: "BM", iso_numeric: "060" },
  { name: "Bielorrusia", alpha_2: "BY", iso_numeric: "112" },
  { name: "Bolivia", alpha_2: "BO", iso_numeric: "068" },
  { name: "Bonaire, San Eustaquio y Saba", alpha_2: "BQ", iso_numeric: "535" },
  { name: "Bosnia y Herzegovina", alpha_2: "BA", iso_numeric: "070" },
  { name: "Botsuana", alpha_2: "BW", iso_numeric: "072" },
  { name: "Brasil", alpha_2: "BR", iso_numeric: "076" },
  { name: "Brunéi", alpha_2: "BN", iso_numeric: "096" },
  { name: "Bulgaria", alpha_2: "BG", iso_numeric: "100" },
  { name: "Burkina Faso", alpha_2: "BF", iso_numeric: "854" },
  { name: "Burundi", alpha_2: "BI", iso_numeric: "108" },
  { name: "Bután", alpha_2: "BT", iso_numeric: "064" },
  { name: "Cabo Verde", alpha_2: "CV", iso_numeric: "132" },
  { name: "Camboya", alpha_2: "KH", iso_numeric: "116" },
  { name: "Camerún", alpha_2: "CM", iso_numeric: "120" },
  { name: "Canadá", alpha_2: "CA", iso_numeric: "124" },
  { name: "Catar", alpha_2: "QA", iso_numeric: "634" },
  { name: "Chad", alpha_2: "TD", iso_numeric: "148" },
  { name: "Chile", alpha_2: "CL", iso_numeric: "152" },
  { name: "China", alpha_2: "CN", iso_numeric: "156" },
  { name: "Chipre", alpha_2: "CY", iso_numeric: "196" },
  { name: "Colombia", alpha_2: "CO", iso_numeric: "170" },
  { name: "Comoras", alpha_2: "KM", iso_numeric: "174" },
  { name: "Corea del Norte", alpha_2: "KP", iso_numeric: "408" },
  { name: "Corea del Sur", alpha_2: "KR", iso_numeric: "410" },
  { name: "Costa de Marfil", alpha_2: "CI", iso_numeric: "384" },
  { name: "Costa Rica", alpha_2: "CR", iso_numeric: "188" },
  { name: "Croacia", alpha_2: "HR", iso_numeric: "191" },
  { name: "Cuba", alpha_2: "CU", iso_numeric: "192" },
  { name: "Curazao", alpha_2: "CW", iso_numeric: "531" },
  { name: "Dinamarca", alpha_2: "DK", iso_numeric: "208" },
  { name: "Dominica", alpha_2: "DM", iso_numeric: "212" },
  { name: "Ecuador", alpha_2: "EC", iso_numeric: "218" },
  { name: "Egipto", alpha_2: "EG", iso_numeric: "818" },
  { name: "El Salvador", alpha_2: "SV", iso_numeric: "222" },
  { name: "EAU", alpha_2: "AE", iso_numeric: "784" },
  { name: "Eritrea", alpha_2: "ER", iso_numeric: "232" },
  { name: "Eslovaquia", alpha_2: "SK", iso_numeric: "703" },
  { name: "Eslovenia", alpha_2: "SI", iso_numeric: "705" },
  { name: "España", alpha_2: "ES", iso_numeric: "724" },
  { name: "Estados Unidos", alpha_2: "US", iso_numeric: "840" },
  { name: "Estonia", alpha_2: "EE", iso_numeric: "233" },
  { name: "Etiopía", alpha_2: "ET", iso_numeric: "231" },
  { name: "Filipinas", alpha_2: "PH", iso_numeric: "608" },
  { name: "Finlandia", alpha_2: "FI", iso_numeric: "246" },
  { name: "Fiyi", alpha_2: "FJ", iso_numeric: "242" },
  { name: "Francia", alpha_2: "FR", iso_numeric: "250" },
  { name: "Gabón", alpha_2: "GA", iso_numeric: "266" },
  { name: "Gambia", alpha_2: "GM", iso_numeric: "270" },
  { name: "Georgia", alpha_2: "GE", iso_numeric: "268" },
  { name: "Ghana", alpha_2: "GH", iso_numeric: "288" },
  { name: "Gibraltar", alpha_2: "GI", iso_numeric: "292" },
  { name: "Granada", alpha_2: "GD", iso_numeric: "308" },
  { name: "Grecia", alpha_2: "GR", iso_numeric: "300" },
  { name: "Groenlandia", alpha_2: "GL", iso_numeric: "304" },
  { name: "Guadalupe", alpha_2: "GP", iso_numeric: "312" },
  { name: "Guam", alpha_2: "GU", iso_numeric: "316" },
  { name: "Guatemala", alpha_2: "GT", iso_numeric: "320" },
  { name: "Guayana Francesa", alpha_2: "GF", iso_numeric: "254" },
  { name: "Guernsey", alpha_2: "GG", iso_numeric: "831" },
  { name: "Guinea", alpha_2: "GN", iso_numeric: "324" },
  { name: "Guinea-Bisáu", alpha_2: "GW", iso_numeric: "624" },
  { name: "Guinea Ecuatorial", alpha_2: "GQ", iso_numeric: "226" },
  { name: "Guyana", alpha_2: "GY", iso_numeric: "328" },
  { name: "Haití", alpha_2: "HT", iso_numeric: "332" },
  { name: "Honduras", alpha_2: "HN", iso_numeric: "340" },
  { name: "Hong Kong", alpha_2: "HK", iso_numeric: "344" },
  { name: "Hungría", alpha_2: "HU", iso_numeric: "348" },
  { name: "India", alpha_2: "IN", iso_numeric: "356" },
  { name: "Indonesia", alpha_2: "ID", iso_numeric: "360" },
  { name: "Irak", alpha_2: "IQ", iso_numeric: "368" },
  { name: "Irán", alpha_2: "IR", iso_numeric: "364" },
  { name: "Irlanda", alpha_2: "IE", iso_numeric: "372" },
  { name: "Isla Bouvet", alpha_2: "BV", iso_numeric: "074" },
  { name: "Isla de Man", alpha_2: "IM", iso_numeric: "833" },
  { name: "Isla de Navidad", alpha_2: "CX", iso_numeric: "162" },
  { name: "Islandia", alpha_2: "IS", iso_numeric: "352" },
  { name: "Islas Caimán", alpha_2: "KY", iso_numeric: "136" },
  { name: "Islas Cocos", alpha_2: "CC", iso_numeric: "166" },
  { name: "Islas Cook", alpha_2: "CK", iso_numeric: "184" },
  { name: "Islas Feroe", alpha_2: "FO", iso_numeric: "234" },
  {
    name: "Islas Georgias del Sur y Sandwich del Sur",
    alpha_2: "GS",
    iso_numeric: "239",
  },
  { name: "Islas Heard y McDonald", alpha_2: "HM", iso_numeric: "334" },
  { name: "Islas Malvinas", alpha_2: "FK", iso_numeric: "238" },
  { name: "Islas Marianas del Norte", alpha_2: "MP", iso_numeric: "580" },
  { name: "Islas Marshall", alpha_2: "MH", iso_numeric: "584" },
  { name: "Islas Pitcairn", alpha_2: "PN", iso_numeric: "612" },
  { name: "Islas Salomón", alpha_2: "SB", iso_numeric: "090" },
  { name: "Islas Turcas y Caicos", alpha_2: "TC", iso_numeric: "796" },
  {
    name: "Islas Ultramarinas Menores de los Estados Unidos",
    alpha_2: "UM",
    iso_numeric: "581",
  },
  { name: "Islas Vírgenes Británicas", alpha_2: "VG", iso_numeric: "092" },
  {
    name: "Islas Vírgenes de los Estados Unidos",
    alpha_2: "VI",
    iso_numeric: "850",
  },
  { name: "Israel", alpha_2: "IL", iso_numeric: "376" },
  { name: "Italia", alpha_2: "IT", iso_numeric: "380" },
  { name: "Jamaica", alpha_2: "JM", iso_numeric: "388" },
  { name: "Japón", alpha_2: "JP", iso_numeric: "392" },
  { name: "Jersey", alpha_2: "JE", iso_numeric: "832" },
  { name: "Jordania", alpha_2: "JO", iso_numeric: "400" },
  { name: "Kazajistán", alpha_2: "KZ", iso_numeric: "398" },
  { name: "Kenia", alpha_2: "KE", iso_numeric: "404" },
  { name: "Kirguistán", alpha_2: "KG", iso_numeric: "417" },
  { name: "Kiribati", alpha_2: "KI", iso_numeric: "296" },
  { name: "Kuwait", alpha_2: "KW", iso_numeric: "414" },
  { name: "Laos", alpha_2: "LA", iso_numeric: "418" },
  { name: "Lesoto", alpha_2: "LS", iso_numeric: "426" },
  { name: "Letonia", alpha_2: "LV", iso_numeric: "428" },
  { name: "Líbano", alpha_2: "LB", iso_numeric: "422" },
  { name: "Liberia", alpha_2: "LR", iso_numeric: "430" },
  { name: "Libia", alpha_2: "LY", iso_numeric: "434" },
  { name: "Liechtenstein", alpha_2: "LI", iso_numeric: "438" },
  { name: "Lituania", alpha_2: "LT", iso_numeric: "440" },
  { name: "Luxemburgo", alpha_2: "LU", iso_numeric: "442" },
  { name: "Macao", alpha_2: "MO", iso_numeric: "446" },
  { name: "Macedonia del Norte", alpha_2: "MK", iso_numeric: "807" },
  { name: "Madagascar", alpha_2: "MG", iso_numeric: "450" },
  { name: "Malasia", alpha_2: "MY", iso_numeric: "458" },
  { name: "Malaui", alpha_2: "MW", iso_numeric: "454" },
  { name: "Maldivas", alpha_2: "MV", iso_numeric: "462" },
  { name: "Mali", alpha_2: "ML", iso_numeric: "466" },
  { name: "Malta", alpha_2: "MT", iso_numeric: "470" },
  { name: "Marruecos", alpha_2: "MA", iso_numeric: "504" },
  { name: "Martinica", alpha_2: "MQ", iso_numeric: "474" },
  { name: "Mauricio", alpha_2: "MU", iso_numeric: "480" },
  { name: "Mauritania", alpha_2: "MR", iso_numeric: "478" },
  { name: "Mayotte", alpha_2: "YT", iso_numeric: "175" },
  { name: "México", alpha_2: "MX", iso_numeric: "484" },
  { name: "Micronesia", alpha_2: "FM", iso_numeric: "583" },
  { name: "Moldavia", alpha_2: "MD", iso_numeric: "498" },
  { name: "Mónaco", alpha_2: "MC", iso_numeric: "492" },
  { name: "Mongolia", alpha_2: "MN", iso_numeric: "496" },
  { name: "Montenegro", alpha_2: "ME", iso_numeric: "499" },
  { name: "Montserrat", alpha_2: "MS", iso_numeric: "500" },
  { name: "Mozambique", alpha_2: "MZ", iso_numeric: "508" },
  { name: "Birmania", alpha_2: "MM", iso_numeric: "104" },
  { name: "Namibia", alpha_2: "NA", iso_numeric: "516" },
  { name: "Nauru", alpha_2: "NR", iso_numeric: "520" },
  { name: "Nepal", alpha_2: "NP", iso_numeric: "524" },
  { name: "Nicaragua", alpha_2: "NI", iso_numeric: "558" },
  { name: "Níger", alpha_2: "NE", iso_numeric: "562" },
  { name: "Nigeria", alpha_2: "NG", iso_numeric: "566" },
  { name: "Niue", alpha_2: "NU", iso_numeric: "570" },
  { name: "Isla Norfolk", alpha_2: "NF", iso_numeric: "574" },
  { name: "Noruega", alpha_2: "NO", iso_numeric: "578" },
  { name: "Nueva Caledonia", alpha_2: "NC", iso_numeric: "540" },
  { name: "Nueva Zelanda", alpha_2: "NZ", iso_numeric: "554" },
  { name: "Omán", alpha_2: "OM", iso_numeric: "512" },
  { name: "Países Bajos", alpha_2: "NL", iso_numeric: "528" },
  { name: "Pakistán", alpha_2: "PK", iso_numeric: "586" },
  { name: "Palaos", alpha_2: "PW", iso_numeric: "585" },
  { name: "Palestina", alpha_2: "PS", iso_numeric: "275" },
  { name: "Panamá", alpha_2: "PA", iso_numeric: "591" },
  { name: "Papúa Nueva Guinea", alpha_2: "PG", iso_numeric: "598" },
  { name: "Paraguay", alpha_2: "PY", iso_numeric: "600" },
  { name: "Perú", alpha_2: "PE", iso_numeric: "604" },
  { name: "Polinesia Francesa", alpha_2: "PF", iso_numeric: "258" },
  { name: "Polonia", alpha_2: "PL", iso_numeric: "616" },
  { name: "Portugal", alpha_2: "PT", iso_numeric: "620" },
  { name: "Puerto Rico", alpha_2: "PR", iso_numeric: "630" },
  { name: "Reino Unido", alpha_2: "GB", iso_numeric: "826" },
  {
    name: "República Árabe Saharaui Democrática",
    alpha_2: "EH",
    iso_numeric: "732",
  },
  { name: "República Centroafricana", alpha_2: "CF", iso_numeric: "140" },
  { name: "República Checa", alpha_2: "CZ", iso_numeric: "203" },
  { name: "República del Congo", alpha_2: "CG", iso_numeric: "178" },
  {
    name: "República Democrática del Congo",
    alpha_2: "CD",
    iso_numeric: "180",
  },
  { name: "República Dominicana", alpha_2: "DO", iso_numeric: "214" },
  { name: "Reunión", alpha_2: "RE", iso_numeric: "638" },
  { name: "Ruanda", alpha_2: "RW", iso_numeric: "646" },
  { name: "Rumania", alpha_2: "RO", iso_numeric: "642" },
  { name: "Rusia", alpha_2: "RU", iso_numeric: "643" },
  { name: "Samoa", alpha_2: "WS", iso_numeric: "882" },
  { name: "Samoa Americana", alpha_2: "AS", iso_numeric: "016" },
  { name: "San Bartolomé", alpha_2: "BL", iso_numeric: "652" },
  { name: "San Cristóbal y Nieves", alpha_2: "KN", iso_numeric: "659" },
  { name: "San Marino", alpha_2: "SM", iso_numeric: "674" },
  { name: "San Martín", alpha_2: "MF", iso_numeric: "663" },
  { name: "San Pedro y Miquelón", alpha_2: "PM", iso_numeric: "666" },
  { name: "San Vicente y las Granadinas", alpha_2: "VC", iso_numeric: "670" },
  {
    name: "Santa Elena, Ascensión y Tristán de Acuña",
    alpha_2: "SH",
    iso_numeric: "654",
  },
  { name: "Santa Lucía", alpha_2: "LC", iso_numeric: "662" },
  { name: "Santo Tomé y Príncipe", alpha_2: "ST", iso_numeric: "678" },
  { name: "Senegal", alpha_2: "SN", iso_numeric: "686" },
  { name: "Serbia", alpha_2: "RS", iso_numeric: "688" },
  { name: "Seychelles", alpha_2: "SC", iso_numeric: "690" },
  { name: "Sierra Leona", alpha_2: "SL", iso_numeric: "694" },
  { name: "Singapur", alpha_2: "SG", iso_numeric: "702" },
  { name: "San Martín", alpha_2: "SX", iso_numeric: "534" },
  { name: "Siria", alpha_2: "SY", iso_numeric: "760" },
  { name: "Somalia", alpha_2: "SO", iso_numeric: "706" },
  { name: "Sri Lanka", alpha_2: "LK", iso_numeric: "144" },
  { name: "Suazilandia", alpha_2: "SZ", iso_numeric: "748" },
  { name: "Sudáfrica", alpha_2: "ZA", iso_numeric: "710" },
  { name: "Sudán", alpha_2: "SD", iso_numeric: "729" },
  { name: "Sudán del Sur", alpha_2: "SS", iso_numeric: "728" },
  { name: "Suecia", alpha_2: "SE", iso_numeric: "752" },
  { name: "Suiza", alpha_2: "CH", iso_numeric: "756" },
  { name: "Surinam", alpha_2: "SR", iso_numeric: "740" },
  { name: "Svalbard y Jan Mayen", alpha_2: "SJ", iso_numeric: "744" },
  { name: "Tailandia", alpha_2: "TH", iso_numeric: "764" },
  { name: "Taiwán (República de China)", alpha_2: "TW", iso_numeric: "158" },
  { name: "Tanzania", alpha_2: "TZ", iso_numeric: "834" },
  { name: "Tayikistán", alpha_2: "TJ", iso_numeric: "762" },
  {
    name: "Territorio Británico del Océano Índico",
    alpha_2: "IO",
    iso_numeric: "086",
  },
  {
    name: "Tierras Australes y Antárticas Francesas",
    alpha_2: "TF",
    iso_numeric: "260",
  },
  { name: "Timor Oriental", alpha_2: "TL", iso_numeric: "626" },
  { name: "Togo", alpha_2: "TG", iso_numeric: "768" },
  { name: "Tokelau", alpha_2: "TK", iso_numeric: "772" },
  { name: "Tonga", alpha_2: "TO", iso_numeric: "776" },
  { name: "Trinidad y Tobago", alpha_2: "TT", iso_numeric: "780" },
  { name: "Túnez", alpha_2: "TN", iso_numeric: "788" },
  { name: "Turkmenistán", alpha_2: "TM", iso_numeric: "795" },
  { name: "Turquía", alpha_2: "TR", iso_numeric: "792" },
  { name: "Tuvalu", alpha_2: "TV", iso_numeric: "798" },
  { name: "Ucrania", alpha_2: "UA", iso_numeric: "804" },
  { name: "Uganda", alpha_2: "UG", iso_numeric: "800" },
  { name: "Uruguay", alpha_2: "UY", iso_numeric: "858" },
  { name: "Uzbekistán", alpha_2: "UZ", iso_numeric: "860" },
  { name: "Vanuatu", alpha_2: "VU", iso_numeric: "548" },
  { name: "Ciudad del Vaticano", alpha_2: "VA", iso_numeric: "336" },
  { name: "Venezuela", alpha_2: "VE", iso_numeric: "862" },
  { name: "Vietnam", alpha_2: "VN", iso_numeric: "704" },
  { name: "Wallis y Futuna", alpha_2: "WF", iso_numeric: "876" },
  { name: "Yemen", alpha_2: "YE", iso_numeric: "887" },
  { name: "Yibuti", alpha_2: "DJ", iso_numeric: "262" },
  { name: "Zambia", alpha_2: "ZM", iso_numeric: "894" },
  { name: "Zimbabue", alpha_2: "ZW", iso_numeric: "716" },
]
