// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type CountryCreate = {
    /**
     * Country name. The backend also accepts `country_name`.
     */
    name?: string;
    /**
     * ISO 3166-1 alpha-2 code.
     */
    alpha_2?: (string | null);
    /**
     * ISO 3166-1 numeric (3 digits). The backend also accepts `iso_numeric`.
     */
    iso_numeric?: (string | null);
    /**
     * Arbitrary key/value data populated over time.
     */
    custom_data?: Record<string, unknown>;
};

export type CountryPublic = {
    /**
     * Country name. The backend returns it as `name`.
     */
    name?: string;
    alpha_2?: (string | null);
    iso_numeric?: (string | null);
    custom_data?: Record<string, unknown>;
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type CountriesPublic = {
    data: Array<CountryPublic>;
    count: number;
};

export type CountryBulkCreate = {
    countries: Array<CountryCreate>;
};

export type CountryBulkCreatePublic = {
    created: Array<CountryPublic>;
    skipped: Array<CountryCreate>;
};

export type CountryUpdate = {
    name?: (string | null);
    alpha_2?: (string | null);
    iso_numeric?: (string | null);
    custom_data?: (Record<string, unknown> | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CountriesReadCountriesData = {
    limit?: number;
    skip?: number;
};

export type CountriesReadCountriesResponse = (CountriesPublic);

export type CountriesCreateCountryData = {
    requestBody: CountryCreate;
};

export type CountriesCreateCountryResponse = (CountryPublic);

export type CountriesCreateCountriesBulkData = {
    requestBody: CountryBulkCreate;
};

export type CountriesCreateCountriesBulkResponse = (CountryBulkCreatePublic);

export type CountriesReadCountryData = {
    id: string;
};

export type CountriesReadCountryResponse = (CountryPublic);

export type CountriesUpdateCountryData = {
    id: string;
    requestBody: CountryUpdate;
};

export type CountriesUpdateCountryResponse = (CountryPublic);

export type CountriesDeleteCountryData = {
    id: string;
};

export type CountriesDeleteCountryResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);